CREATE DATABASE realestate;
CREATE TABLE Property (
  PropertyID INT NOT NULL IDENTITY(1,1),
  PropertyName VARCHAR(255) NOT NULL,
  Address VARCHAR(255) NOT NULL,
  City VARCHAR(255) NOT NULL,
  State VARCHAR(255) NOT NULL,
  Country VARCHAR(255) NOT NULL,
  ZipCode VARCHAR(10) NOT NULL,
  Description TEXT,
  Price DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (PropertyID)
);

-- Create PropertyImage table
CREATE TABLE PropertyImage (
  ImageID INT NOT NULL IDENTITY(1,1),
  PropertyID INT NOT NULL,
  ImageName VARCHAR(255) NOT NULL,
  ImageURL VARCHAR(255) NOT NULL,
  PRIMARY KEY (ImageID),
  FOREIGN KEY (PropertyID) REFERENCES Property(PropertyID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create Agent table
CREATE TABLE Agent (
  AgentID INT NOT NULL IDENTITY(1,1),
  FirstName VARCHAR(255) NOT NULL,
  LastName VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  Phone VARCHAR(20) NOT NULL,
  Address VARCHAR(255) NOT NULL,
  City VARCHAR(255) NOT NULL,
  State VARCHAR(255) NOT NULL,
  Country VARCHAR(255) NOT NULL,
  ZipCode VARCHAR(10) NOT NULL,
  PRIMARY KEY (AgentID)
);

-- Create PropertyAgent table
CREATE TABLE PropertyAgent (
  PropertyAgentID INT NOT NULL IDENTITY(1,1),
  PropertyID INT NOT NULL,
  AgentID INT NOT NULL,
  PRIMARY KEY (PropertyAgentID),
  FOREIGN KEY (PropertyID) REFERENCES Property(PropertyID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (AgentID) REFERENCES Agent(AgentID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create Inquiry table
CREATE TABLE Inquiry (
  InquiryID INT NOT NULL IDENTITY(1,1),
  PropertyID INT NOT NULL,
  FirstName VARCHAR(255) NOT NULL,
  LastName VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  Phone VARCHAR(20) NOT NULL,
  Message TEXT,
  PRIMARY KEY (InquiryID),
  FOREIGN KEY (PropertyID) REFERENCES Property(PropertyID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create User table
CREATE TABLE [User] (
  UserID INT NOT NULL IDENTITY(1,1),
  FirstName VARCHAR(255) NOT NULL,
  LastName VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Address VARCHAR(255) NOT NULL,
  City VARCHAR(255) NOT NULL,
  State VARCHAR(255) NOT NULL,
  Country VARCHAR(255) NOT NULL,
  ZipCode VARCHAR(10) NOT NULL,
  PRIMARY KEY (UserID)
);